### ISSUE TITLE
Document endpoint schema

### ISSUE THREAD

**Issue by mehrdadmms** [Microflow-xyz/pocket-frontned#6]
# Goal
Discuss and describe how backend and frontend are going to communicate. 
Please write down the schema for each endpoint over here. 

# How
- [x] Decide how frontend and backend are going to communicate 
- [ ] Layout the schema

**Comment by mostafa1647** [comment]
Based on my meeting with @ahmadyazdanii we decided to move forward with restful arch for communicating between frontend and backend.

CC: @mehrdadmms, @GhanbarT

**Comment by ahmadyazdanii** [comment]
Based on the meeting with @mostafa1647, We confirmed on following response schema: 

Body response:
```json
{
   "metrics": { ... }
}
```

Also, We have 4 patterns for responding metrics:

1) For string-type value metrics

```json
"metric name": {
   "value": ""
}
```
2) For number-type value metrics

```json
"metric name": {
   "value": 0.0
}
```
3) For bar-chart metrics

```json
"metric name": {
   "values": [
      {
        "date": "",
        "value": 0.0
      },
    ]
}
```

4) For stacked-bar-chart metrics

```json
"metric name": {
   "values": [
      {
        "date": "",
        "values": [
           {
             "name": "",
             "value": 0.0
           },
        ]
      },
    ]
}
```

**Comment by ahmadyazdanii** [comment]
Pokt dashboard API document is ready in [the link](https://www.postman.com/microflow/workspace/microflow/collection/25228095-ec6f5503-846c-47c7-95fa-dfcdbc1f91c5?action=share&creator=25228095).
